version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12-node

    working_directory: ~/app
    steps:
      - checkout
      - run: sudo apt install antlr4 # install antlr
      - run: npm install # install npm dependency
      - run: npm run build # build parser code
      - run: npm run test # javascript test
      - run: go test -v -mod=vendor ./... -race -coverprofile=coverage.txt -covermode=atomic # test with coverage
      - run: bash <(curl -s https://codecov.io/bash)