version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12-node

    working_directory: ~/app
    steps:
      - checkout
      # test with coverage
      - run: npm install
      - run: npm run build
      - run: go test -v -mod=vendor ./... -race -coverprofile=coverage.txt -covermode=atomic
      - run: bash <(curl -s https://codecov.io/bash)